### ISSUE TITLE
Реверс температуры

### ISSUE THREAD

**Issue by kluv58** [GyverLibs/GyverNTC#6]
При нагреве термистора температура уменьшается. Термистор NTC, подключение правильное: NTC к GND, резистор к +5V, средняя точка к A0. Не пойму, где косяк?

**Comment by GyverLibs** [comment]
в подключении или типе термистора

**Comment by kluv58** [comment]
Вопрос решен. Просто попалась ущербная библиотека на Гит Хабе. В папке SRC не хватало GuverNTC.cpp. Переустановил и все пошло.
