### ISSUE TITLE
GyverNTC - there is a bug

### ISSUE THREAD

**Issue by banzay-2021** [GyverLibs/GyverNTC#7]
Привет Алекс.
Решил и тут запостить, вдруг почта подкачает.
Во первых огромное тебе спасибо за твои ролики и бесплатные библиотеки.
Пишу тебе впервые, но твой канал частенько попадается в ютюбе со всякими самоделками. Один из первых роликов что я смотрел - это квадрокоптер из сантеха.или что то в этом духе. Но сейчас не об этом Я тут недавно начал ковырять ардуинку и решил попробовать одну из твоих библиотек - GyverNTC. В частности я про метод getTempAverage(); Баг заключается в том, что при аргументе 110 и выше результаты этого метода непредсказуемые, а все потому что переменная aver имеет тип uint16_t. Я поставил uint32_t и при значении аргумента 50 000 000 все стабильно и код выполняется за 99 мс на атмеге328 с выводом на Олед дисплей с твоей же библиотекой GyverOLED. А при аргументе равным 20 - получаем 75 мс. Но сейчас не об этом.
Я понимаю что среднее от 50 000 000 итерациями скорее всего уже дофига, но 1000, для моих нужд самое оно, ну ты понял, для более сильного сглаживания шума термодатчика.
Я понимаю что ты оптимизировал код чтобы он меньше кушал памяти и я у себя могу изменить твою библиотеку, но думаю что или в описании добавить что итераций не более 110 или заметить на uint32_t aver = 0; и итераций не более 50 000 000 )))
К слову (если таки будет версия v1.5.2) меня можно и не упоминать. Я не обижусь )))

Спасибо за твои труды и усилия!!!
Всех благ.

**Comment by banzay-2021** [comment]
Спасибо за ответ.
Можно и внешним фильтром, но скорость получения данных, как ты заметил, упадет. А в итоге это тоже будет +- среднее значение за промежуток времени. А почему я увеличиваю с 20 до 250-1000 ? Потому что при выводе на дисплей показания прызают в пределах 0,5 - 0,8 градуса, что немного напрягает. А при бОльшем количестве измерений показания начинают прыгать в пределах 0,01 - 0,02 градуса. Что визуально, ИМХО, гораздо приятнее. И тут не про точность ищмерений. Как ты отметил в видео термопара + питание, "шумят" довольно в больших приделах и ловить 0,01 градуса тут точно безсмыслено, но если округлять до 0,1 на дисплее, то .... ну да ладно. На вкус и цвет.... кто какие задачи выполняет.
Просто при использовании библиотеки я поймал не задокументированное ограничение, которое проявилось в том что усредненна температура при более 110 итераций показала на предсказуемое значенее 65,95 а должно было показать комнатную темпераруру 24,48

Ок. В любом случае спасибо.

**Comment by GyverLibs** [comment]
> внешним фильтром, но скорость получения данных упадет

То есть 100мс на чтение датчика никак не смущают?)) Такие вещи фильтруются по времени и никак иначе, особенно если учесть что термистор довольно инертная штука и в принципе быстро менять значения не может, все что меняется быстро - это шум. Также термистор изначально имеет точность +- лапоть, получать с него цифру с разрешением 0.01 абсолютно бессмысленно лол, это значение не имеет ничего общего с реальностью)))

**Comment by banzay-2021** [comment]
Смущает. Но и 74 мс тоже не мало. И ты прав в отношении датчика.  Но если применять твою либу для самопального инкубатора, то 100 мс не критично.
А вот в отношении описания кода, не хватает в описании, что getTempAverage() может принимать значения от 1 до 127 максимум а для надежности 120. Потому что при 128 метод возвращает 403.43 а при 127 - 25.19. Это должно было смутить тебя. А как смутит новичка в ардуино, когда он получит 403 а не 25. Я новичек в ардуино, но PHP-перю уже 12 лет. Отсюда и дотошность к описанию кода, сори... Правда я начинал писать код в 1991 году для процессора Z80 и комп паяли с нуля включая клавиатру, а писали код на аудио кассету ))) А в крутом компе было всего 128 КБ памяти ))) Во были времемена )))

 Такая запись съедает всего 14 байт памяти (судя по информации с терминала) против текущей

    // прочитать усреднённую температуру с пина, можно указать к-во усреднений
    float getTempAverage(uint16_t samples = 20) {
        uint32_t aver = 0;
        for (uint16_t i = 0; i < samples; i++) aver += analogRead(_pin);
        return computeTemp((float)aver / samples, _res);
    }

 Но за то увеличивает устойчивость кода от дурака (ну или пытливого ума ))) ) И да, аргумент samples может быть максимум 2^16-1 = 65535, а это 7413 мс ))))) Что точно не приемлимо даже для инкубатора )))
 
 Просто было бы супер, если ты напишешь в доке для метода getTempAverage() ограничения от 1 до 125. И все )))

**Comment by GyverLibs** [comment]
Дело не в 14 байтах памяти, а в эффективности и скорости работы. В любом случае, повторюсь, усреднение АЦП в таких масштабах делать нельзя, это неправильно. Ограничение 1.. 125 также бессмысленное. На сумму влияет как разрешение АЦП, так и само значение. 125 тут просто какая то случайная цифра из головы

**Comment by banzay-2021** [comment]
Т.е. если в метод getTempAverage() передать 0 или 128, то результат функция вернет корректный?

**Comment by GyverLibs** [comment]
Это не так работает

**Comment by GyverLibs** [comment]
Оно вернёт бред и при значении 20, если АЦП имеет разрешение 12 бит и температура высокая. Поэтому очень важно, как это работает. Я написал в доку, что больше 20 передавать нельзя, вопрос закрыт

**Comment by banzay-2021** [comment]
Супер. Спасибо. Закрыт.
